# **Cell 1: Import Libraries**

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# **Cell 2: Website URL**

In [2]:
url = "http://books.toscrape.com/"
response = requests.get(url)

print("Status Code:", response.status_code)

Status Code: 200

# **Cell 3: Parse HTML**

In [3]:
soup = BeautifulSoup(response.text, "html.parser")

print(soup.title.text)

    All products | Books to Scrape - Sandbox

# **Cell 4: Find All Books**

In [4]:
books = soup.find_all("article", class_="product_pod")

print("Total Books on Page:", len(books))

Total Books on Page: 20

# **Cell 5: Extract Data**

In [5]:
books_data = []

for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    availability = book.find("p", class_="instock availability").text.strip()
    rating = book.p["class"][1]

    books_data.append({
        "Title": title,
        "Price": price,
        "Availability": availability,
        "Rating": rating
    })

print("Data Extracted Successfully!")

Data Extracted Successfully!

# **Cell 6: Create DataFrame**

In [6]:
df = pd.DataFrame(books_data)

df.head()

                                   Title    Price Availability Rating
0                   A Light in the Attic  Â£51.77     In stock  Three
1                     Tipping the Velvet  Â£53.74     In stock    One
2                             Soumission  Â£50.10     In stock    One
3                          Sharp Objects  Â£47.82     In stock   Four
4  Sapiens: A Brief History of Humankind  Â£54.23     In stock   Five

# **Cell 7: Save Dataset**

In [7]:
df.to_csv("books_data.csv", index=False)

print("CSV File Saved Successfully!")

CSV File Saved Successfully!

In [8]:
from google.colab import files

files.download("books_data.csv")

# **Cell 9: Basic Data Analysis (Bonus)**

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         20 non-null     object
 1   Price         20 non-null     object
 2   Availability  20 non-null     object
 3   Rating        20 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes
None

In [10]:
df.describe(include="all")

                       Title    Price Availability Rating
count                     20       20           20     20
unique                    20       20            1      5
top     A Light in the Attic  Â£51.77     In stock    One
freq                       1        1           20      6

In [11]:
df["Rating"].value_counts()

Rating
One      6
Five     4
Four     4
Three    3
Two      3
Name: count, dtype: int64

In [12]:
df["Availability"].value_counts()

Availability
In stock    20
Name: count, dtype: int64

# **Cell 10: Display Complete Dataset**

In [13]:
df

,Title,Price,Availability,Rating
0,A Light in the Attic,Â£51.77,In stock,Three
1,Tipping the Velvet,Â£53.74,In stock,One
2,Soumission,Â£50.10,In stock,One
3,Sharp Objects,Â£47.82,In stock,Four
4,Sapiens: A Brief History of Humankind,Â£54.23,In stock,Five
5,The Requiem Red,Â£22.65,In stock,One
6,The Dirty Little Secrets of Getting Your Dream...,Â£33.34,In stock,Four
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,In stock,Three
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,In stock,Four
9,The Black Maria,Â£52.15,In stock,One
10,"Starving Hearts (Triangular Trade Trilogy, #1)",Â£13.99,In stock,Two
11,Shakespeare's Sonnets,Â£20.66,In stock,Four
12,Set Me Free,Â£17.46,In stock,Five
13,Scott Pilgrim's Precious Little Life (Scott Pi...,Â£52.29,In stock,Five
14,Rip it Up and Start Again,Â£35.02,In stock,Five
15,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,In stock,Three
16,Olio,Â£23.88,In stock,One
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,In stock,One
18,Libertarianism for Beginners,Â£51.33,In stock,Two
19,It's Only the Himalayas,Â£45.17,In stock,Two